# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OutfitOfTheDay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OutfitOfTheDay
  pod 'SnapKit', '~> 4.0.0'
  pod 'Then'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'


end
